### ISSUE TITLE
Missing owner and modality

### ISSUE THREAD

**Issue by georgemoralis** [dustinkredmond/FXAlert#1]
Great lib easy to used 👍 

It would be nice to have these as well

**Comment by dustinkredmond** [comment]
Glad you enjoy it. I whipped this lib up in a matter of a few hours, so I'm sure there's much more that I'm missing. 

Modality and owner should definitely be included, I will work on implementing this today. Thanks for the notice!

**Comment by dustinkredmond** [comment]
@georgemoralis 
I created a commit which includes the below two methods in the `AlertBuilder` class. These features won't exist for the shorthand methods e.g. `FXAlert.showInfo("someText")` and the like.

Added:
`public AlertBuilder withInitModality(Modality m)`
`public AlertBuilder withInitOwner(Window w)`

It will be available from version 2.1.0, the new version has been deployed to Maven central repo.
