### ISSUE TITLE
jfxtras-styles with jmetro not working

### ISSUE THREAD

**Issue by zhan-ge** [dustinkredmond/FXAlert#3]
There is no way to setup the jmetro, eg.

```java
jMetro.setScene(alertBuilder.getAlert().getScene());
```

or some way setup style with CSS file path string.

**Comment by dustinkredmond** [comment]
Hi @zhan-ge, you need to style the `DialogPane` of the alert. Try to use `FXAlert.info().withStylesheet()` or `FXAlert.info().withStyle()`. 

Alternatively, you can also do something like `FXAlert.info().getAlert()` if you want a reference to the underlying JavaFX `Alert`. From there, you can get the `DialogPane`'s `Scene` and style it that way. You could do something like: `FXAlert.info().getAlert().getDialogPane().getScene()`.

I don't want to cater specifically to the JMetro theme library, as if we support one theme, we'll eventually end up with requests to support them all. Let me know if my previous suggestions are what you're looking for. 

Thanks for using FXAlert!
