### ISSUE TITLE
Add Java Platform Module System (JPMS) compatibility

### ISSUE THREAD

**Issue by peter277** [dustinkredmond/FXAlert#5]
Current library jar is not modular (due to missing module-info.class) and needs to be used as an automodule in modular projects.

Given the relatively straightforward dependencies, I have created a module-info.java file and linked a pull request. As a result the pull request also bumps up the required Java version to 9 - but if we still want to keep Java 8 compatibility, please let me know and I'm happy to amend the pull request so that a multi-release jar is generated which would preserve compatibility.

This would also fix Maven warning when compiling a modular project: `Required filename-based automodules detected: [...]. Please don't publish this project to a public artifact repository!`

cc @dustinkredmond

**Comment by dustinkredmond** [comment]
Merged into main branch. I'll try to push a release to Maven today. Thanks.
